name: weather-api
webroot: app
services:
  myservice:
    type: python
    command:
      - uvicorn app.main:app --port 8086 --host 0.0.0.0 --proxy-headers
    port: 8086
    ssl: false
events:
  pre-start:
    - myservice: pip3 install --no-cache-dir --upgrade -r requirements.txt

proxy:
  myservice:
    - weather-api.lndo.site
